version: 2.1

jobs:
  validate-changes:
    docker:
      # pre-commit package is included since 20.10
      - image: ubuntu:20.10
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run pre-commit checks
          command: |
            apt update && apt install -y shellcheck pre-commit git
            pre-commit run --all-files

  workspace-ubuntu-base:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            ./.circleci/build_image.sh base/Dockerfile gitpod/workspace-ubuntu-base
            docker save gitpod/workspace-ubuntu-base -o workspace-ubuntu-base.tar
          no_output_timeout: 20m
      - persist_to_workspace:
          root: .
          paths:
            - workspace-ubuntu-base.tar

  workspace-rhel7-ubi-base:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            ./.circleci/build_image.sh base/Dockerfile gitpod/workspace-rhel7-ubi-base
            docker save gitpod/workspace-rhel7-ubi-base -o workspace-rhel7-ubi-base.tar
          no_output_timeout: 20m
      - persist_to_workspace:
          root: .
          paths:
            - workspace-rhel7-ubi-base.tar

  workspace-ubuntu-full:
    docker:
      - image: csweichel/dazzle:latest
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i workspace-ubuntu-base.tar
            ./.circleci/dazzle_build_image.sh full/Dockerfile gitpod/workspace-ubuntu-full workspace-ubuntu-full.tar
          no_output_timeout: 30m
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/dazzle/
            cp full/*.xml ~/test-results/dazzle
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/dazzle
      - persist_to_workspace:
          root: .
          paths:
            - workspace-ubuntu-full.tar

  workspace-ubuntu-full-vnc:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i workspace-ubuntu-full.tar
            ./.circleci/build_image.sh full-vnc/Dockerfile gitpod/workspace-ubuntu-full-vnc
            docker save gitpod/workspace-ubuntu-full-vnc -o workspace-ubuntu-full-vnc.tar
      - persist_to_workspace:
          root: .
          paths:
            - workspace-ubuntu-full-vnc.tar

  mdbook:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i workspace-ubuntu-full.tar
            ./.circleci/build_image.sh mdbook/Dockerfile gitpod/mdbook
          no_output_timeout: 30m

  workspace-dotnet:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i workspace-ubuntu-full.tar
            ./.circleci/build_image.sh dotnet/Dockerfile gitpod/workspace-dotnet
          no_output_timeout: 60m

  workspace-dotnet-vnc:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i workspace-ubuntu-full-vnc.tar
            ./.circleci/build_image.sh dotnet-vnc/Dockerfile gitpod/workspace-dotnet-vnc
          no_output_timeout: 30m

  workspace-dotnet-lts:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i workspace-ubuntu-full.tar
            ./.circleci/build_image.sh dotnet-lts/Dockerfile gitpod/workspace-dotnet-lts
          no_output_timeout: 60m

  workspace-dotnet-lts-vnc:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i workspace-ubuntu-full-vnc.tar
            ./.circleci/build_image.sh dotnet-lts-vnc/Dockerfile gitpod/workspace-dotnet-lts-vnc
          no_output_timeout: 30m

  workspace-postgres:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i workspace-ubuntu-full.tar
            ./.circleci/build_image.sh postgres/Dockerfile gitpod/workspace-postgres
          no_output_timeout: 30m

  workspace-mysql:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i workspace-ubuntu-full.tar
            ./.circleci/build_image.sh mysql/Dockerfile gitpod/workspace-mysql
          no_output_timeout: 30m

  workspace-mongodb:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i workspace-ubuntu-full.tar
            ./.circleci/build_image.sh mongodb/Dockerfile gitpod/workspace-mongodb

  workspace-flutter:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i workspace-ubuntu-full.tar
            ./.circleci/build_image.sh flutter/Dockerfile gitpod/workspace-flutter

  workspace-gecko:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i workspace-ubuntu-full-vnc.tar
            ./.circleci/build_image.sh gecko/Dockerfile gitpod/workspace-gecko
          no_output_timeout: 60m

  workspace-wasm:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i workspace-ubuntu-full.tar
            ./.circleci/build_image.sh wasm/Dockerfile gitpod/workspace-wasm
          no_output_timeout: 30m

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate-changes
      - workspace-ubuntu-base:
          requires:
            - validate-changes
      - workspace-ubuntu-full:
          requires:
            - workspace-ubuntu-base
      - workspace-ubunut-full-vnc:
          requires:
            - workspace-ubuntu-full
      - mdbook:
          requires:
            - workspace-ubuntu-full
      - workspace-dotnet:
          requires:
            - workspace-ubuntu-full
      - workspace-dotnet-vnc:
          requires:
            - workspace-ubuntu-full-vnc
      - workspace-dotnet-lts:
          requires:
            - workspace-ubuntu-full
      - workspace-dotnet-lts-vnc:
          requires:
            - workspace-ubuntu-full-vnc
      - workspace-postgres:
          requires:
            - workspace-ubuntu-full
      - workspace-mysql:
          requires:
            - workspace-ubuntu-full
      - workspace-mongodb:
          requires:
            - workspace-ubuntu-full
      - workspace-flutter:
          requires:
            - workspace-ubuntu-full
      - workspace-gecko:
          requires:
            - workspace-ubuntu-full-vnc
      - workspace-wasm:
          requires:
            - workspace-ubuntu-full
